[2025-02-07T14:57:00.962+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T14:57:00.976+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_versioned.pre_deployment_checks manual__2025-02-07T14:56:58.779135+00:00 [queued]>
[2025-02-07T14:57:00.981+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_versioned.pre_deployment_checks manual__2025-02-07T14:56:58.779135+00:00 [queued]>
[2025-02-07T14:57:00.982+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T14:57:00.992+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): pre_deployment_checks> on 2025-02-07 14:56:58.779135+00:00
[2025-02-07T14:57:00.999+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=779) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T14:57:01.002+0000] {standard_task_runner.py:72} INFO - Started process 780 to run task
[2025-02-07T14:57:01.003+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_versioned', 'pre_deployment_checks', 'manual__2025-02-07T14:56:58.779135+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_versioned.py', '--cfg-path', '/tmp/tmpnz_6hx2v']
[2025-02-07T14:57:01.005+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask pre_deployment_checks
[2025-02-07T14:57:01.051+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_versioned.pre_deployment_checks manual__2025-02-07T14:56:58.779135+00:00 [running]> on host 35f5723d0861
[2025-02-07T14:57:01.114+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_versioned' AIRFLOW_CTX_TASK_ID='pre_deployment_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T14:56:58.779135+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T14:56:58.779135+00:00'
[2025-02-07T14:57:01.116+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T14:57:01.117+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T14:57:01.117+0000] {logging_mixin.py:190} INFO - Current task name:pre_deployment_checks state:running start_date:2025-02-07 14:57:00.977002+00:00
[2025-02-07T14:57:01.117+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned and current dag run status:running
[2025-02-07T14:57:01.118+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T14:57:01.118+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-07T14:57:01.119+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv3gbxil0p --system-site-packages --python=python
[2025-02-07T14:57:01.120+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:57:01.669+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 158ms
[2025-02-07T14:57:01.670+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv3gbxil0p, clear=False, no_vcs_ignore=False, global=True)
[2025-02-07T14:57:01.670+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-07T14:57:01.671+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-07T14:57:01.671+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-07T14:57:01.691+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv3gbxil0p/bin/pip install -r /tmp/venv3gbxil0p/requirements.txt
[2025-02-07T14:57:01.693+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:57:02.629+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv3gbxil0p/requirements.txt (line 1)) (2.1.4)
[2025-02-07T14:57:02.635+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv3gbxil0p/requirements.txt (line 1)) (1.26.4)
[2025-02-07T14:57:02.635+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv3gbxil0p/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-07T14:57:02.636+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv3gbxil0p/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:57:02.636+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv3gbxil0p/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:57:02.639+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venv3gbxil0p/requirements.txt (line 1)) (1.17.0)
[2025-02-07T14:57:03.015+0000] {process_utils.py:194} INFO - 
[2025-02-07T14:57:03.016+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-07T14:57:03.016+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-07T14:57:03.080+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv3gbxil0p/bin/python /tmp/venv-calld0pzuv24/script.py /tmp/venv-calld0pzuv24/script.in /tmp/venv-calld0pzuv24/script.out /tmp/venv-calld0pzuv24/string_args.txt /tmp/venv-calld0pzuv24/termination.log
[2025-02-07T14:57:03.084+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:57:05.307+0000] {process_utils.py:194} INFO - [2025-02-07T14:57:05.306+0000] {script.py:23} INFO - Starting pre-deployment checks...
[2025-02-07T14:57:05.310+0000] {process_utils.py:194} INFO - [2025-02-07T14:57:05.309+0000] {script.py:38} INFO - Pre-deployment checks completed
[2025-02-07T14:57:05.727+0000] {python.py:240} INFO - Done. Returned value was: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-07T14:57:05.309401'}
[2025-02-07T14:57:05.754+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T14:57:05.755+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_versioned, task_id=pre_deployment_checks, run_id=manual__2025-02-07T14:56:58.779135+00:00, execution_date=20250207T145658, start_date=20250207T145700, end_date=20250207T145705
[2025-02-07T14:57:05.762+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T14:57:05.762+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T14:57:05.763+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned queued_at:2025-02-07 14:56:58.791553+00:00
[2025-02-07T14:57:05.763+0000] {logging_mixin.py:190} INFO - Task hostname:35f5723d0861 operator:PythonVirtualenvOperator
[2025-02-07T14:57:05.787+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T14:57:05.821+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T14:57:05.824+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
