[2025-02-10T07:56:07.331+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T07:56:07.344+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_versioned.download_stack manual__2025-02-10T07:55:55.839065+00:00 [queued]>
[2025-02-10T07:56:07.351+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_versioned.download_stack manual__2025-02-10T07:55:55.839065+00:00 [queued]>
[2025-02-10T07:56:07.352+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T07:56:07.360+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): download_stack> on 2025-02-10 07:55:55.839065+00:00
[2025-02-10T07:56:07.376+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13061) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T07:56:07.378+0000] {standard_task_runner.py:72} INFO - Started process 13062 to run task
[2025-02-10T07:56:07.378+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_versioned', 'download_stack', 'manual__2025-02-10T07:55:55.839065+00:00', '--job-id', '418', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_versioned.py', '--cfg-path', '/tmp/tmphrs5pqi4']
[2025-02-10T07:56:07.379+0000] {standard_task_runner.py:105} INFO - Job 418: Subtask download_stack
[2025-02-10T07:56:07.414+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_versioned.download_stack manual__2025-02-10T07:55:55.839065+00:00 [running]> on host 35f5723d0861
[2025-02-10T07:56:07.476+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_versioned' AIRFLOW_CTX_TASK_ID='download_stack' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T07:55:55.839065+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T07:55:55.839065+00:00'
[2025-02-10T07:56:07.478+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T07:56:07.478+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T07:56:07.478+0000] {logging_mixin.py:190} INFO - Current task name:download_stack state:running start_date:2025-02-10 07:56:07.344790+00:00
[2025-02-10T07:56:07.479+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned and current dag run status:running
[2025-02-10T07:56:07.479+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T07:56:07.479+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T07:56:07.481+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvqijhij4s --system-site-packages --python=python
[2025-02-10T07:56:07.482+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T07:56:08.215+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 300ms
[2025-02-10T07:56:08.216+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvqijhij4s, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T07:56:08.217+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T07:56:08.217+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T07:56:08.217+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T07:56:08.234+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvqijhij4s/bin/pip install -r /tmp/venvqijhij4s/requirements.txt
[2025-02-10T07:56:08.236+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T07:56:09.345+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvqijhij4s/requirements.txt (line 1)) (2.1.4)
[2025-02-10T07:56:09.350+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvqijhij4s/requirements.txt (line 1)) (1.26.4)
[2025-02-10T07:56:09.350+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvqijhij4s/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T07:56:09.350+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvqijhij4s/requirements.txt (line 1)) (2024.2)
[2025-02-10T07:56:09.351+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvqijhij4s/requirements.txt (line 1)) (2024.2)
[2025-02-10T07:56:09.354+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvqijhij4s/requirements.txt (line 1)) (1.17.0)
[2025-02-10T07:56:09.775+0000] {process_utils.py:194} INFO - 
[2025-02-10T07:56:09.776+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T07:56:09.776+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T07:56:09.852+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvqijhij4s/bin/python /tmp/venv-callhyvltnjf/script.py /tmp/venv-callhyvltnjf/script.in /tmp/venv-callhyvltnjf/script.out /tmp/venv-callhyvltnjf/string_args.txt /tmp/venv-callhyvltnjf/termination.log
[2025-02-10T07:56:09.853+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T07:56:12.008+0000] {process_utils.py:194} INFO - [2025-02-10T07:56:12.007+0000] {script.py:30} INFO - Starting download stack...
[2025-02-10T07:56:22.066+0000] {process_utils.py:194} INFO - [2025-02-10T07:56:22.062+0000] {script.py:46} INFO - Writing download report to to: /opt/***/data/download_report.json
[2025-02-10T07:56:22.075+0000] {process_utils.py:194} INFO - [2025-02-10T07:56:22.071+0000] {script.py:50} INFO - Download stack completed:
[2025-02-10T07:56:22.076+0000] {process_utils.py:194} INFO - Total size: 1200.0MB
[2025-02-10T07:56:22.083+0000] {process_utils.py:194} INFO - Total time: 240s
[2025-02-10T07:56:22.085+0000] {process_utils.py:194} INFO - Download speed: 5.0MB/s
[2025-02-10T07:56:22.877+0000] {python.py:240} INFO - Done. Returned value was: {'stacks': ['baseos', 'gi'], 'total_size_mb': 1200.0, 'total_time_seconds': 240, 'download_speed_mbs': 5.0, 'status': 'success', 'details': [{'stack': 'baseos', 'size_mb': 1000, 'status': 'completed', 'time': 180}, {'stack': 'gi', 'size_mb': 200, 'status': 'completed', 'time': 60}], 'timestamp': '2025-02-10T07:56:22.062067'}
[2025-02-10T07:56:22.957+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T07:56:22.958+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_versioned, task_id=download_stack, run_id=manual__2025-02-10T07:55:55.839065+00:00, execution_date=20250210T075555, start_date=20250210T075607, end_date=20250210T075622
[2025-02-10T07:56:22.967+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T07:56:22.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T07:56:22.969+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned queued_at:2025-02-10 07:55:55.851477+00:00
[2025-02-10T07:56:22.969+0000] {logging_mixin.py:190} INFO - Task hostname:35f5723d0861 operator:PythonVirtualenvOperator
[2025-02-10T07:56:23.010+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T07:56:23.033+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T07:56:23.035+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
