[2025-02-10T08:04:46.840+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T08:04:46.877+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_versioned.run_pre_check manual__2025-02-10T08:04:12.770666+00:00 [queued]>
[2025-02-10T08:04:46.885+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_versioned.run_pre_check manual__2025-02-10T08:04:12.770666+00:00 [queued]>
[2025-02-10T08:04:46.886+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T08:04:46.895+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): run_pre_check> on 2025-02-10 08:04:12.770666+00:00
[2025-02-10T08:04:46.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T08:04:46.906+0000] {standard_task_runner.py:72} INFO - Started process 13283 to run task
[2025-02-10T08:04:46.907+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_versioned', 'run_pre_check', 'manual__2025-02-10T08:04:12.770666+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_versioned.py', '--cfg-path', '/tmp/tmptm2f8zm1']
[2025-02-10T08:04:46.908+0000] {standard_task_runner.py:105} INFO - Job 428: Subtask run_pre_check
[2025-02-10T08:04:46.957+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_versioned.run_pre_check manual__2025-02-10T08:04:12.770666+00:00 [running]> on host 35f5723d0861
[2025-02-10T08:04:47.060+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_versioned' AIRFLOW_CTX_TASK_ID='run_pre_check' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T08:04:12.770666+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T08:04:12.770666+00:00'
[2025-02-10T08:04:47.061+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T08:04:47.062+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T08:04:47.069+0000] {logging_mixin.py:190} INFO - Current task name:run_pre_check state:running start_date:2025-02-10 08:04:46.877698+00:00
[2025-02-10T08:04:47.069+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned and current dag run status:running
[2025-02-10T08:04:47.070+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T08:04:47.071+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T08:04:47.073+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvrmdrjirx --system-site-packages --python=python
[2025-02-10T08:04:47.075+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T08:04:47.888+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 292ms
[2025-02-10T08:04:47.890+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvrmdrjirx, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T08:04:47.890+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T08:04:47.891+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T08:04:47.891+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T08:04:47.910+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvrmdrjirx/bin/pip install -r /tmp/venvrmdrjirx/requirements.txt
[2025-02-10T08:04:47.911+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T08:04:49.012+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvrmdrjirx/requirements.txt (line 1)) (2.1.4)
[2025-02-10T08:04:49.020+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvrmdrjirx/requirements.txt (line 1)) (1.26.4)
[2025-02-10T08:04:49.020+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvrmdrjirx/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T08:04:49.021+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvrmdrjirx/requirements.txt (line 1)) (2024.2)
[2025-02-10T08:04:49.022+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvrmdrjirx/requirements.txt (line 1)) (2024.2)
[2025-02-10T08:04:49.024+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvrmdrjirx/requirements.txt (line 1)) (1.17.0)
[2025-02-10T08:04:49.460+0000] {process_utils.py:194} INFO - 
[2025-02-10T08:04:49.461+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T08:04:49.461+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T08:04:49.523+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-02-10T08:04:49.535+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvrmdrjirx/bin/python /tmp/venv-call6tbtok7b/script.py /tmp/venv-call6tbtok7b/script.in /tmp/venv-call6tbtok7b/script.out /tmp/venv-call6tbtok7b/string_args.txt /tmp/venv-call6tbtok7b/termination.log
[2025-02-10T08:04:49.536+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T08:04:51.871+0000] {process_utils.py:194} INFO - [2025-02-10T08:04:51.869+0000] {script.py:23} INFO - Starting run pre-checks...
[2025-02-10T08:04:51.873+0000] {process_utils.py:194} INFO - [2025-02-10T08:04:51.870+0000] {script.py:26} INFO - Pre Deployment Report: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-10T08:04:21.097720'}
[2025-02-10T08:04:51.874+0000] {process_utils.py:194} INFO - [2025-02-10T08:04:51.871+0000] {script.py:41} INFO - Pre-checks completed:
[2025-02-10T08:04:51.874+0000] {process_utils.py:194} INFO - Total memory usage: 1536%
[2025-02-10T08:04:51.875+0000] {process_utils.py:194} INFO - Status: PASS
[2025-02-10T08:04:52.276+0000] {python.py:240} INFO - Done. Returned value was: {'total_memory_usage_mb': 1536, 'checks_passed': True, 'timestamp': '2025-02-10T08:04:51.871807'}
[2025-02-10T08:04:52.324+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T08:04:52.325+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_versioned, task_id=run_pre_check, run_id=manual__2025-02-10T08:04:12.770666+00:00, execution_date=20250210T080412, start_date=20250210T080446, end_date=20250210T080452
[2025-02-10T08:04:52.335+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T08:04:52.335+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T08:04:52.336+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_versioned queued_at:2025-02-10 08:04:12.922195+00:00
[2025-02-10T08:04:52.336+0000] {logging_mixin.py:190} INFO - Task hostname:35f5723d0861 operator:PythonVirtualenvOperator
[2025-02-10T08:04:52.371+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T08:04:52.397+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T08:04:52.398+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
