[2025-02-07T08:54:31.328+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T08:54:31.336+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_e2e_tests.start_e2e_tests manual__2025-02-07T08:54:29.844560+00:00 [queued]>
[2025-02-07T08:54:31.339+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_e2e_tests.start_e2e_tests manual__2025-02-07T08:54:29.844560+00:00 [queued]>
[2025-02-07T08:54:31.339+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-07T08:54:31.345+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): start_e2e_tests> on 2025-02-07 08:54:29.844560+00:00
[2025-02-07T08:54:31.349+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6636) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T08:54:31.350+0000] {standard_task_runner.py:72} INFO - Started process 6637 to run task
[2025-02-07T08:54:31.351+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_e2e_tests', 'start_e2e_tests', 'manual__2025-02-07T08:54:29.844560+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/run_e2e_tests.py', '--cfg-path', '/tmp/tmp9fcri_su']
[2025-02-07T08:54:31.352+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask start_e2e_tests
[2025-02-07T08:54:31.384+0000] {task_command.py:467} INFO - Running <TaskInstance: run_e2e_tests.start_e2e_tests manual__2025-02-07T08:54:29.844560+00:00 [running]> on host ***-worker
[2025-02-07T08:54:31.420+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_e2e_tests' AIRFLOW_CTX_TASK_ID='start_e2e_tests' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T08:54:29.844560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T08:54:29.844560+00:00'
[2025-02-07T08:54:31.421+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T08:54:31.421+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T08:54:31.422+0000] {logging_mixin.py:190} INFO - Current task name:start_e2e_tests state:running start_date:2025-02-07 08:54:31.336421+00:00
[2025-02-07T08:54:31.422+0000] {logging_mixin.py:190} INFO - Dag name:run_e2e_tests and current dag run status:running
[2025-02-07T08:54:31.422+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T08:54:31.423+0000] {run_e2e_tests.py:25} INFO - Starting end-to-end tests
[2025-02-07T08:54:34.423+0000] {run_e2e_tests.py:27} INFO - Tests ran successfully
[2025-02-07T08:54:34.425+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-07T08:54:34.435+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T08:54:34.436+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=run_e2e_tests, task_id=start_e2e_tests, run_id=manual__2025-02-07T08:54:29.844560+00:00, execution_date=20250207T085429, start_date=20250207T085431, end_date=20250207T085434
[2025-02-07T08:54:34.447+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T08:54:34.448+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T08:54:34.448+0000] {logging_mixin.py:190} INFO - Dag name:run_e2e_tests queued_at:2025-02-07 08:54:29.882785+00:00
[2025-02-07T08:54:34.449+0000] {logging_mixin.py:190} INFO - Task hostname:***-worker operator:PythonOperator
[2025-02-07T08:54:34.478+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T08:54:34.498+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T08:54:34.499+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
